### ISSUE TITLE
Improve Unsupervised Vocalization (syllable) detection. Compare to existing outputs (Cezar to send data)

### ISSUE THREAD

**Issue by tyiannak** [tyiannak/amvoc#1]
The goal of this issue is to create a robust and more accurate syllable detector (unsupervised).
Towards this end, we will experiment with feature extraction and thresholding parameters. Results will be compared wrt other similar software and/or human generated ground truth.

**Comment by tyiannak** [comment]
@cvargas4 what is the last column of the csv file? (e.g. number 13 in the following row)
**TGExampleWithTimeStamps,B148_test,685,296.0448,296.2272,13**

**Comment by cvargas4** [comment]
> @cvargas4 what is the last column of the csv file? (e.g. number 13 in the following row)
> **TGExampleWithTimeStamps,B148_test,685,296.0448,296.2272,13**

The last column is listing which "Repertoire Unit (RU)" that USV belongs to. In this case, I asked MUPET to cluster into 40 RUs. That syllable in your example happens to be in the 13th cluster. I believe this is done by k-means.

So far we (the lab) have not used these RUs as they are not necessarily consistant across analyses (very much within batch/recording).

**Comment by tyiannak** [comment]
as we discussed today @cvargas4 , these are the subtasks to be completed before finalizing this issue. 
1) change F1/F2 to be static **(code)**
2) add some energy/spectral_energy ratio in the thresholding rule (it seems that true vocalizations have ratios closer to 1) **(code)**
3) more parameters tuned in evaluation.py **(code)**
4) re run for the whole recordings **(report)**
5) prepare report + examples **(QA)**

**Comment by tyiannak** [comment]
I've updated the results and comparison to mupet [here](https://drive.google.com/file/d/1O4X1wrHaWXo3uSsXDDd0VptPyfS7K4JL/view?usp=sharing) (for the best parameters). @cvargas4 it would be great if you could randomly select some areas from the 2 spectrogram plots to estimate precision and recall of the amvoc detector. 

You can also commend the respective document [here](https://docs.google.com/document/d/1UBewkrDgpVw00hUwNSCjwUxUEvDvxsImsoUFpC0QXJA/edit#). 

I am also working on adding the MSA comparison and after that I think we're done with the vocalization detection task.

**Comment by tyiannak** [comment]
@cvargas4 document and results updated. The following is missing to close this issue:
1) @cvargas4 to proceed with Precision/Recall evaluation (see document for the link to the 2 html files to be used for the evaluation)
2) @tyiannak and @cvargas4 to check the low agreement results with MSA

**Comment by tyiannak** [comment]
Can be considered closed after precision/recall has been added
